function GetIDEDashboardWizards(){
   // return [{ "name": "Integration Project", "iconURL":"null", "wizards": [{ "id" :"1dashboard.wizardLink.esb.project", "name":"org.wso2.developerstudio.eclipse.artifact.newesbproject", "priority":"1"}, { "id" :"dashboard.wizardLink.esb.connector.project", "name":"org.wso2.developerstudio.eclipse.artifact.newconnectorartifact", "priority":"2"}, { "id" :"2dashboard.wizardLink.esb.proxy", "name":"org.wso2.developerstudio.eclipse.artifact.newproxyservice", "priority":"2"}, { "id" :"1dashboard.wizardLink.integration.project", "name":"org.wso2.developerstudio.eclipse.artifact.newintegrationproject", "priority":"2"}, { "id" :"3dashboard.wizardLink.esb.endpoint", "name":"org.wso2.developerstudio.eclipse.artifact.newendpointartifact", "priority":"3"}, { "id" :"6dashboard.wizardLink.esb.sequence", "name":"org.wso2.developerstudio.eclipse.artifact.newsequenceartifact", "priority":"6"}, { "id" :"7dashboard.wizardLink.esb.localentry", "name":"org.wso2.developerstudio.eclipse.artifact.newlocalentry", "priority":"7"}, { "id" :"8dashboard.wizardLink.esb.synapse.api", "name":"org.wso2.developerstudio.eclipse.artifact.synapse.api.wizard", "priority":"8"}, { "id" :"8dashboard.wizardLink.esb.template", "name":"org.wso2.developerstudio.eclipse.artifact.newtemplate", "priority":"8"}, { "id" :"9dashboard.wizardLink.esb.mediator", "name":"org.wso2.developerstudio.eclipse.artifact.newmediatorartifact", "priority":"9"}, { "id" :"9dashboard.wizardLink.esb.task", "name":"org.wso2.developerstudio.eclipse.artifact.task.wizard", "priority":"9"}, { "id" :"dashboard.wizardLink.esb.inboundendpoint", "name":"org.wso2.developerstudio.eclipse.artifact.newinboundendpointartifact", "priority":"10"}, { "id" :"91dashboard.wizardLink.esb.messageprocessor", "name":"org.wso2.developerstudio.eclipse.artifact.messageprocessor.wizard", "priority":"10"}, { "id" :"91dashboard.wizardLink.esb.messagestore", "name":"org.wso2.developerstudio.eclipse.artifact.messagestore.wizard", "priority":"10"}, { "id" :"dashboard.wizardLink.esb.synapse", "name":"org.wso2.developerstudio.eclipse.artifact.synapseartifact", "priority":"11"}]},{ "name": "Repository", "iconURL":"null", "wizards": [{ "id" :"dashboard.wizardLink.general.project", "name":"org.wso2.developerstudio.eclipse.general.project", "priority":"2"}]}]

    return "[{ \"name\": \"Integration Project\", \"iconURL\":\"null\", \"wizards\": [{ \"id\" :\"1dashboard.wizardLink.esb.project\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newesbproject\", \"priority\":\"1\"}, { \"id\" :\"dashboard.wizardLink.esb.connector.project\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newconnectorartifact\", \"priority\":\"2\"}, { \"id\" :\"2dashboard.wizardLink.esb.proxy\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newproxyservice\", \"priority\":\"2\"}, { \"id\" :\"1dashboard.wizardLink.integration.project\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newintegrationproject\", \"priority\":\"2\"}, { \"id\" :\"3dashboard.wizardLink.esb.endpoint\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newendpointartifact\", \"priority\":\"3\"}, { \"id\" :\"6dashboard.wizardLink.esb.sequence\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newsequenceartifact\", \"priority\":\"6\"}, { \"id\" :\"7dashboard.wizardLink.esb.localentry\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newlocalentry\", \"priority\":\"7\"}, { \"id\" :\"8dashboard.wizardLink.esb.synapse.api\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.synapse.api.wizard\", \"priority\":\"8\"}, { \"id\" :\"8dashboard.wizardLink.esb.template\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newtemplate\", \"priority\":\"8\"}, { \"id\" :\"9dashboard.wizardLink.esb.mediator\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newmediatorartifact\", \"priority\":\"9\"}, { \"id\" :\"9dashboard.wizardLink.esb.task\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.task.wizard\", \"priority\":\"9\"}, { \"id\" :\"dashboard.wizardLink.esb.inboundendpoint\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.newinboundendpointartifact\", \"priority\":\"10\"}, { \"id\" :\"91dashboard.wizardLink.esb.messageprocessor\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.messageprocessor.wizard\", \"priority\":\"10\"}, { \"id\" :\"91dashboard.wizardLink.esb.messagestore\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.messagestore.wizard\", \"priority\":\"10\"}, { \"id\" :\"dashboard.wizardLink.esb.synapse\", \"name\":\"org.wso2.developerstudio.eclipse.artifact.synapseartifact\", \"priority\":\"11\"}]},{ \"name\": \"Repository\", \"iconURL\":\"null\", \"wizards\": [{ \"id\" :\"dashboard.wizardLink.general.project\", \"name\":\"org.wso2.developerstudio.eclipse.general.project\", \"priority\":\"2\"}]}]";
}


function GetWizardIconData(id){
    return "iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAABo0lEQVR4nGP4//8/AzJ+UskgcLdeqOF2j9HtG5Pdnx0rVt62zo+BHSYPV/i5jUH9TZ/0mpcL3Z59uzLlz/8jnf//T4/6/2Vv3d/N8SL75jowMEM09DOo/pynevDrjvg3f+4u/P//zKT//19v/v+/xe3//1SV///zdf4/XhH7c3GgcBtYw58Fas/+vVjz///dJf//FxlBFM1L/P//xbL//8uNIfwu1/+rk9Uet+oyiDN87+f2+DDf8t6fJyv+/T/Z//9/mipE0dn6///3F0HYQLGPW7L+T3QRWwp2/9MqBv6HPRqXfj0GauoPhCjqATrp9cz//3fn//9/vw/Mnughcwnu6cs5DPzXOkxu/jkBdOqCiP//r7dDNCDhST5K91CC9FgGd86rA/n/0BWC8J/n0/43W0mcR9GwJ5LB+NbiqPfoij9e7fg/K0r3RakapweKhh2RrAFP9zb8ACn69XjS/0uL477NCVG+32ErtjFPhskCJeJA+EChxobnxyb/21/v9HR+gPixHguumEplBg5kNSgatibK7FgXp9gw2YJBFD3JwDAARqKEE90Q6qsAAAAASUVORK5CYII="}

function GetWizardDescription(id){
    return "test";
}